service: serverless-demo

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  profile: Administrator
  stage: dev
  region: us-east-1

functions:
  api:
    handler: src/api/api.handler
    events:
      - http:
          path: /api
          method: GET
          cors: true
  todo:
    handler: src/api/todo.handler

  todos:
    handler: src/api/todos.handler

plugins:
  - serverless-offline
